# Generated by Django 4.1.13 on 2024-04-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('EmployeeID', models.AutoField(primary_key=True, serialize=False)),
                ('Manager', models.CharField(max_length=500)),
                ('EmployeeName', models.CharField(max_length=500)),
                ('PhotoFileName', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Managers',
            fields=[
                ('ManagerID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
