# Generated by Django 4.1.13 on 2024-04-20 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_route_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='name',
            field=models.CharField(default='Ruchir', max_length=500),
            preserve_default=False,
        ),
    ]
